# Generated by Django 5.0.1 on 2024-01-14 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generations',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
    ]
